export { default as StartPage } from './Start'
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as PlanPage } from './Plan'
export { default as SharePage } from './Share'
export { default as LoginPage } from './Login'
